config/routes.rb
Rails.application.routes.draw do

  root 'home#index'  # point http://127.0.0.1:3000/ to home controller's index action

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :sessions, only: [:new, :create, :destroy]  
  
  get 'signup', to: 'users#new', as: 'signup'  
  get 'login', to: 'sessions#new', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'  
  
  resources :users  
  
  resources :employees
  post 'employees/save', to: 'employees#save', as: 'save' # can add a path to any new action in the controller 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord

  validate :name_required

  def name_required
    if not name.present?
      errors.add(:name, "is required")
    end  
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password  
  
  validates :first_name,  
            presence: true  
  
  validates :last_name,  
            presence: true  
  
  validates :age,  
            presence: true  
  
  validates :email,  
            presence: true,  
            uniqueness: true,  
            format: {  
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i  
            }  
  
  def to_s  
    "#{first_name} #{last_name}"  
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session 
  include Error::ErrorHandler
  
  private   
  def current_user   
    User.where(id: session[:user_id]).first   
  end   
  helper_method :current_user   

  def logged_in?
    !current_user.nil?  
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  layout "employees"
  include MessageConstants
  
  def index
    @employees = Employee.all.to_json
  end

  def show
    @employees = Employee.all
  end

  def save
    result = EmployeesCrud.call(params[:data])
    
    if result[:success]
      render json: { message: EMP_SAVED, employees: Employee.all }, status: :ok
    else
      render json: { message: EMP_NOT_SAVED, error: "#{result[:error]}", employees: result[:employees] }, status: :unprocessable_entity
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new   
  end   

  def create   
    user = User.find_by_email(params[:email])   
    
    if user && user.authenticate(params[:password])   
      session[:user_id] = user.id   
      redirect_to root_url, notice: 'Logged in!'   
    else   
      render :new   
    end   
  end  

  def destroy   
    session[:user_id] = nil   
    redirect_to root_url, notice: 'Logged out!'   
  end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new
  end

  def create   
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :age, :email, :password))
    if @user.save   
      session[:user_id] = @user.id   
      redirect_to root_url, notice: 'User successfully created.'   
    else   
      render :new   
    end   
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_constants.rb
module MessageConstants

  EMP_SAVED = "Employees saved"
  EMP_NOT_SAVED = "Employees not saved"
  EMP_CRUD_FAILED = "Employees crud failed"
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_employee.html.erb
  <tr>
    <td><%= employee.id %></td> 
    <td><%= employee.id %></td> 
    <td><%= employee.gender %></td> 
    <td><%= employee.designation %></td> 
    <td><%= employee.department %></td>
  </tr>


 

app/views/employees/index.html.erb
<script>
    var employees = <%= raw @employees%>; //@employees is returned from employees_controller.rb
</script>
<div style="text-align: center; font-size: x-large; font-weight: bold;"> Manage Employees </div>
<div style="text-align: center;">
  
  <br>
  <br>
  <div ng-controller="EmployeesCtrl">
    <div ui-grid="gridOptions" class="employeesGrid" ui-grid-edit ui-grid-row-edit ui-grid-validate ui-grid-cellNav style="display: inline-block"></div>
    <br>
    <br>
    <button ng-click="addEmployee()"> Add Employee</button>
    <button ng-click="save()"> Save </button>
    <button ng-click="cancel()"> Cancel </button>    
  </div>
</div>

app/views/employees/show.html.erb
 <div style="text-align: center;"><h2>Employees List</h2></div>

<div style="align-self: right;display: flex;justify-content: center;">
  <table>
    <thead>
      <tr>
        <th>Id</th> 
        <th>Name</th> 
        <th>Gender</th> 
        <th>Designation</th> 
        <th>Department</th>
      </tr>  
    <thead>
      
    <tbody>
    <% @employees.each do |employee| %>
      <% cache employee do %>
        <%= render employee %>
      <% end %>
    <% end %>
    <tbody>
  </table>
</div>
 

app/views/layouts/_header.html.erb
<div id="user_header">  
  <% if current_user %>  
    <div> 
      <div style="float:left"><%= link_to "View Employees", "employees/show" %> | <%= link_to "Manage Employees", employees_path %></div>
      <div style="float:right"> Logged in as <%= current_user.email %>. | <%= link_to "Log Out", logout_path %></div>     
    </div>
  <% else %>  
    <div> <%= link_to "Sign Up", signup_path %> or <%= link_to "Log In", login_path %> </div>
  <% end %>   
</div>  

<% flash.each do |key, value| %>  
  <%= content_tag(:div, class: "alert alert-#{key}") do %>  
    <p><%= value %></p>  
  <% end %>  
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="angularUsage">

  <head>    
    <title>Rails Usage</title>
    <script src="/release/ui-grid.validate.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>   
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>

  </body>

</html>

app/views/layouts/employees.html.erb
<!DOCTYPE html>
<html ng-app="angularUsage">

  <head>    
    <title>Manage Employees</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>   
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= yield %>

  </body>

</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f|%>
  <%= f.label :first_name%><br>
  <%= f.text_field :first_name%><br>

  <%= f.label :last_name%><br>
  <%= f.text_field :last_name%><br>

  <%= f.label :age%><br>
  <%= f.number_field :age%><br>

  <%= f.label :email%><br>
  <%= f.text_field :email%><br>


  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>

<%end%>